# Generated by Django 4.1.5 on 2023-06-15 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apelldio_materno', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=80, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=80, null=True)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.artista')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.categoria')),
            ],
        ),
    ]
