# Generated by Django 4.1.5 on 2023-06-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='apelldio_materno',
            new_name='apellido_materno',
        ),
    ]
